-- AlterTable
ALTER TABLE "Business" ADD COLUMN     "password" TEXT NOT NULL DEFAULT '123456',
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL,
ALTER COLUMN "city" DROP NOT NULL,
ALTER COLUMN "state" DROP NOT NULL,
ALTER COLUMN "zip" DROP NOT NULL,
ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "category" DROP NOT NULL;
